# Generated by Django 3.2 on 2022-11-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='version',
        ),
    ]
