# Generated by Django 3.2 on 2022-11-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0002_remove_aimodel_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='is_selected',
            field=models.BooleanField(default=True),
        ),
    ]
