# Generated by Django 3.2 on 2022-11-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlanguage', '0003_alter_aimodel_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='version',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
